### ISSUE TITLE
Notification with Observables question

### ISSUE THREAD

**Issue by cecilphillip** [aspnet/EventNotification#13]
I see event notifications and I can't help but think Rx :). Is there a plan / thought to leverage the work that's already being done there with Observables and Subjects ?

**Comment by danroth27** [comment]
@rynowak 

No plans at this time - we are just trying to build something specific to our needs and our tooling partners. 

We don't think Rx is a good fit because:
1. We have a ShouldNotify concept, which allows listeners to indicate if they are interested in an event. Rx doesn't really have that concept, and
2. We think its important to be able to see all of the events together for a given request/context. Turning individual events into separate streams would make them harder to consume with the proper correlation.

**Comment by rynowak** [comment]
@cecilphillip - I'm afraid we actually shared the wrong conclusion with you. We've been in discussions with the BCL team, and the APIs here are going to move deeper into the stack.

They are planning to support `IObservable`. https://github.com/dotnet/corefx/pull/2932
